import type { StarterTemplate } from './starter-template.type.js';

export function createContentFiles(): StarterTemplate[] {
  return [createContentTypesTypeTs(), createContentTypesTs()];
}

function createContentTypesTypeTs(): StarterTemplate {
  return {
    content: [
      "export type StarterContentTypeKind = 'collection' | 'single';",
      '',
      'export interface StarterContentFieldDefinition {',
      '  key: string;',
      '  label: string;',
      '  required: boolean;',
      "  type: 'boolean' | 'date' | 'number' | 'richtext' | 'text';",
      '  repeatable: boolean;',
      '  sortOrder: number;',
      '}',
      '',
      'export interface StarterContentTypeDefinition {',
      '  displayName: string;',
      '  fields: readonly StarterContentFieldDefinition[];',
      '  kind: StarterContentTypeKind;',
      '  slug: string;',
      '}',
      '',
    ].join('\n'),
    path: 'src/content-types.type.ts',
  };
}

function createContentTypesTs(): StarterTemplate {
  return {
    content: [
      "import type { StarterContentFieldDefinition, StarterContentTypeDefinition } from './content-types.type.js';",
      '',
      'export const starterContentTypeMigrationStatements = [',
      "  'CREATE TABLE IF NOT EXISTS content_types (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, kind TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)',",
      "  'CREATE TABLE IF NOT EXISTS content_fields (id TEXT PRIMARY KEY, content_type_id TEXT NOT NULL, field_key TEXT NOT NULL, label TEXT NOT NULL, type TEXT NOT NULL, required INTEGER NOT NULL DEFAULT 0, repeatable INTEGER NOT NULL DEFAULT 0, sort_order INTEGER NOT NULL DEFAULT 0, settings_json TEXT NOT NULL DEFAULT ''{}'', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (content_type_id) REFERENCES content_types(id) ON DELETE CASCADE)',",
      '] as const;',
      '',
      'function quote(value: string): string {',
      '  return JSON.stringify(value);',
      '}',
      '',
      'function booleanToSql(value: boolean): string {',
      '  return value ? \'1\' : \'0\';',
      '}',
      '',
      'export function createContentTypeInsertSql(definition: StarterContentTypeDefinition): string {',
      '  return [',
      "    'INSERT INTO content_types (id, display_name, kind, slug) VALUES (',",
      '    quote(definition.slug),',
      "    ', ',",
      '    quote(definition.displayName),',
      "    ', ',",
      '    quote(definition.kind),',
      "    ', ',",
      '    quote(definition.slug),',
      "    ')',",
      '  ].join(\'\');',
      '}',
      '',
      'export function createContentFieldInsertSql(contentTypeId: string, field: StarterContentFieldDefinition): string {',
      '  return [',
      "    'INSERT INTO content_fields (id, content_type_id, field_key, label, type, required, repeatable, sort_order) VALUES (',",
      '    quote(`${contentTypeId}:${field.key}`),',
      "    ', ',",
      '    quote(contentTypeId),',
      "    ', ',",
      '    quote(field.key),',
      "    ', ',",
      '    quote(field.label),',
      "    ', ',",
      '    quote(field.type),',
      "    ', ',",
      '    booleanToSql(field.required),',
      "    ', ',",
      '    booleanToSql(field.repeatable),',
      "    ', ',",
      '    String(field.sortOrder),',
      "    ')',",
      '  ].join(\'\');',
      '}',
      '',
    ].join('\n'),
    path: 'src/content-types.ts',
  };
}
