import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createServer } from "./app.js";
import { runApiagexMcpStdioServer } from "./mcp-server.js";
import { ensureLocalServerPaths, resolveLocalServerConfig } from "./server-config.js";
import { bootstrapOwner } from "./owner-bootstrap.js";
import { generateApiagexTypes } from "./typegen.js";
import {
  openMigratedSqliteAdapter,
  openMySqlAdapter,
  openPostgresAdapter,
  type ApiagexDatabase,
} from "@apiagex/database";
import type { RuntimeCliOptions, RuntimeCliResult, StartedApiagexServer, StartServerOptions } from "./runtime.type.js";

const runtimeVersion = "0.8.18";

export async function startApiagex(options: StartServerOptions = {}): Promise<StartedApiagexServer | undefined> {
  return startApiagexServer(options);
}

export async function startApiagexServer(options: StartServerOptions = {}): Promise<StartedApiagexServer | undefined> {
  const env = options.env ?? process.env;
  const host = options.host ?? env.HOST ?? "127.0.0.1";
  const port = options.port ?? Number(env.PORT ?? 4000);
  const config = options.config ?? resolveLocalServerConfig(env, options.cwd ?? process.cwd());
  await ensureLocalServerPaths(config);
  const database = await openRuntimeDatabase(config);
  if (options.initialOwner) await bootstrapInitialOwner(database, options.initialOwner);
  const server = createServer({
    ...config,
    database,
    ...(options.customRoutes ? { customRoutes: options.customRoutes } : {}),
  });
  try {
    await server.listen({ host, port });
    console.log(`Apiagex listening on http://${host}:${port}`);
    console.log(databaseLocationLine(config));
    console.log(`Apiagex uploads path: ${config.uploadsPath}`);
    return server;
  } catch (error) {
    server.log.error(error);
    console.error(startupErrorMessage(host, port, error));
    process.exitCode = 1;
    return undefined;
  }
}

export async function runRuntimeCli(args: string[], options: RuntimeCliOptions = {}): Promise<RuntimeCliResult> {
  const command = args[0] ?? "--help";
  if (command === "--help" || command === "-h") return ok(renderRuntimeHelp());
  if (command === "--version" || command === "-v") return ok(`apiagex ${runtimeVersion}\n`);
  if (command === "smoke") return smoke(options);
  if (command === "types") return generateTypes(args.slice(1), options);
  if (command === "ai") return ai(args.slice(1), options);
  if (command === "mcp") return mcp(options);
  if (command === "build") return ok("Apiagex runtime does not need a project build. Run apiagex smoke to verify.\n");
  if (command === "dev" || command === "start") {
    const startOptions = {
      ...(options.cwd === undefined ? {} : { cwd: options.cwd }),
      ...(options.env === undefined ? {} : { env: options.env }),
    };
    await startApiagexServer(startOptions);
    return ok("");
  }
  return fail(`Unknown apiagex command: ${command}\n\n${renderRuntimeHelp()}`);
}

export function renderRuntimeHelp(): string {
  return `apiagex ${runtimeVersion}

Usage:
  apiagex dev       Start the Apiagex server for local development.
  apiagex start     Start the Apiagex server.
  apiagex smoke     Verify the runtime health route without a long-running server.
  apiagex types     Generate TypeScript helpers from the current database schemas.
  apiagex ai context Create or refresh .apiagex/codex.md.
  apiagex ai token   Create a temporary automation token through the Admin API.
  apiagex ai doctor  Check local AI/Codex setup without printing secrets.
  apiagex mcp       Start the Apiagex MCP server over stdio.
  apiagex build     Print build guidance for generated projects.

Options:
  --out <path>       apiagex types output file. Default: src/apiagex-types.ts.
  --base-url <url>   apiagex ai base URL. Default: APIAGEX_BASE_URL or HOST/PORT.
  -h, --help        Show help.
  -v, --version     Show version.

Environment:
  APIAGEX_DATABASE_PROVIDER sqlite, postgres, or mysql. Default: sqlite.
  PORT                    Server port. Default: 4000.
  HOST                    Server host. Default: 127.0.0.1.
  APIAGEX_DATABASE_PATH   SQLite path. Default: .apiagex/apiagex.sqlite.
  APIAGEX_DATABASE_URL    PostgreSQL/MySQL URL when provider is postgres or mysql.
  APIAGEX_UPLOADS_PATH    Uploads path. Default: .apiagex/uploads.
  APIAGEX_SECRET          App secret generated by create-apiagex.
  APIAGEX_BASE_URL        Base URL for AI setup commands.
  APIAGEX_ADMIN_TOKEN     Owner session token used only by apiagex ai token.
  APIAGEX_AUTOMATION_TOKEN Temporary token used by AI clients.
  APIAGEX_OWNER_EMAIL     Optional first owner bootstrap email.
  APIAGEX_OWNER_PASSWORD  Optional first owner bootstrap password. Remove after first start.
`;
}

async function mcp(options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const cwd = options.cwd ?? process.cwd();
  const env = await runtimeEnv(cwd, options);
  await runApiagexMcpStdioServer({
    automationToken: env.APIAGEX_AUTOMATION_TOKEN,
    baseUrl: resolveAiBaseUrl(env, undefined),
  });
  return ok("");
}

async function ai(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const subcommand = args[0] ?? "--help";
  if (subcommand === "--help" || subcommand === "-h") return ok(renderAiHelp());
  if (subcommand === "context") return aiContext(args.slice(1), options);
  if (subcommand === "doctor") return aiDoctor(args.slice(1), options);
  if (subcommand === "token") return aiToken(args.slice(1), options);
  return fail(`Unknown apiagex ai command: ${subcommand}\n\n${renderAiHelp()}`);
}

function renderAiHelp(): string {
  return `apiagex ai

Usage:
  apiagex ai context  Create or refresh .apiagex/codex.md.
  apiagex ai token    Create a temporary automation token.
  apiagex ai doctor   Check local AI/Codex setup.

Options:
  --base-url <url>       Base URL. Default: APIAGEX_BASE_URL or HOST/PORT.
  --admin-token <token>  Owner session token for apiagex ai token.
  --name <name>          Token name. Default: Codex setup.
  --ttl-minutes <mins>   Token TTL. Default: 60.
  --scopes <list>        Comma-separated automation scopes.
`;
}

async function aiContext(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const parsed = parseAiArgs(args);
  if (typeof parsed === "string") return fail(parsed);
  const cwd = options.cwd ?? process.cwd();
  const env = await runtimeEnv(cwd, options);
  const contextPath = join(cwd, ".apiagex", "codex.md");
  await mkdir(join(cwd, ".apiagex"), { recursive: true });
  await writeFile(contextPath, renderRuntimeCodexContext(resolveAiBaseUrl(env, parsed.baseUrl)), "utf8");
  return ok(`Wrote ${contextPath}\nKeep real tokens in APIAGEX_AUTOMATION_TOKEN or APIAGEX_ADMIN_TOKEN, never in source files.\n`);
}

async function aiDoctor(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const parsed = parseAiArgs(args);
  if (typeof parsed === "string") return fail(parsed);
  const cwd = options.cwd ?? process.cwd();
  const env = await runtimeEnv(cwd, options);
  const contextPath = join(cwd, ".apiagex", "codex.md");
  const contextExists = await fileExists(contextPath);
  const lines = [
    "Apiagex AI setup:",
    `- Base URL: ${resolveAiBaseUrl(env, parsed.baseUrl)}`,
    `- Context file: ${contextExists ? "found" : "missing"} (${contextPath})`,
    `- APIAGEX_AUTOMATION_TOKEN: ${env.APIAGEX_AUTOMATION_TOKEN ? "set" : "not set"}`,
    `- APIAGEX_ADMIN_TOKEN: ${env.APIAGEX_ADMIN_TOKEN ? "set" : "not set"}`,
    "No token values are printed by doctor.",
    "",
  ];
  return ok(lines.join("\n"));
}

async function aiToken(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const parsed = parseAiArgs(args);
  if (typeof parsed === "string") return fail(parsed);
  const cwd = options.cwd ?? process.cwd();
  const env = await runtimeEnv(cwd, options);
  const adminToken = parsed.adminToken ?? env.APIAGEX_ADMIN_TOKEN;
  if (!adminToken) return fail("Set APIAGEX_ADMIN_TOKEN or pass --admin-token to create an automation token.\n");
  const baseUrl = resolveAiBaseUrl(env, parsed.baseUrl);
  const response = await fetch(`${baseUrl}/api/admin/automation-tokens`, {
    body: JSON.stringify({
      name: parsed.name ?? "Codex setup",
      scopes: parsed.scopes,
      ttlMinutes: parsed.ttlMinutes ?? 60,
    }),
    headers: {
      authorization: `Bearer ${adminToken}`,
      "content-type": "application/json",
    },
    method: "POST",
  });
  const body: unknown = await response.json().catch(async () => ({ error: await response.text() }));
  if (!response.ok || !isAutomationTokenCreateResponse(body)) {
    return fail(`Automation token creation failed (${response.status}): ${JSON.stringify(body)}\n`);
  }
  return ok([
    "Created automation token.",
    `export APIAGEX_AUTOMATION_TOKEN=${body.token}`,
    "Warning: do not commit this token or write it into source files.",
    `Expires at: ${body.tokenRecord.expiresAt}`,
    `Scopes: ${body.tokenRecord.scopes.join(", ")}`,
    "",
  ].join("\n"));
}

function parseAiArgs(args: string[]): {
  adminToken?: string;
  baseUrl?: string;
  name?: string;
  scopes?: string[];
  ttlMinutes?: number;
} | string {
  const parsed: { adminToken?: string; baseUrl?: string; name?: string; scopes?: string[]; ttlMinutes?: number } = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? "";
    if (arg === "--base-url") {
      const value = args[index + 1];
      if (!value) return "Use --base-url <url>.";
      parsed.baseUrl = stripTrailingSlash(value);
      index += 1;
    } else if (arg === "--admin-token") {
      const value = args[index + 1];
      if (!value) return "Use --admin-token <token>.";
      parsed.adminToken = value;
      index += 1;
    } else if (arg === "--name") {
      const value = args[index + 1];
      if (!value) return "Use --name <name>.";
      parsed.name = value;
      index += 1;
    } else if (arg === "--ttl-minutes") {
      const value = args[index + 1];
      if (!value || !Number.isInteger(Number(value))) return "Use --ttl-minutes <minutes>.";
      parsed.ttlMinutes = Number(value);
      index += 1;
    } else if (arg === "--scopes") {
      const value = args[index + 1];
      if (!value) return "Use --scopes <comma-separated-scopes>.";
      parsed.scopes = value.split(",").map((scope) => scope.trim()).filter(Boolean);
      index += 1;
    } else return `Unknown apiagex ai option: ${arg}`;
  }
  return parsed;
}

async function runtimeEnv(cwd: string, options: RuntimeCliOptions): Promise<Record<string, string>> {
  return { ...await readProjectEnv(cwd), ...process.env, INIT_CWD: cwd, ...options.env };
}

function resolveAiBaseUrl(env: Record<string, string>, baseUrl: string | undefined): string {
  if (baseUrl) return stripTrailingSlash(baseUrl);
  if (env.APIAGEX_BASE_URL) return stripTrailingSlash(env.APIAGEX_BASE_URL);
  return `http://${env.HOST ?? "127.0.0.1"}:${env.PORT ?? "4000"}`;
}

function stripTrailingSlash(value: string): string {
  return value.replace(/\/+$/, "");
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch (error) {
    if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return false;
    throw error;
  }
}

function renderRuntimeCodexContext(baseUrl: string): string {
  return `# Apiagex Codex Context

This project uses Apiagex as the backend.

## Connection

- Base URL: ${baseUrl}
- Base URL env: APIAGEX_BASE_URL
- Automation token env: APIAGEX_AUTOMATION_TOKEN
- Admin token env, only when creating a temporary automation token: APIAGEX_ADMIN_TOKEN

Do not commit real tokens. Keep APIAGEX_AUTOMATION_TOKEN and APIAGEX_ADMIN_TOKEN in your local shell, CI secret store, or ignored .env files only.

## Safe Workflow

1. Read this file and inspect the frontend request.
2. Call \`GET $APIAGEX_BASE_URL/api/health\`.
3. Use APIAGEX_AUTOMATION_TOKEN for Apiagex setup work.
4. Inspect existing schemas, workflows, and routes before creating new ones.
5. Prefer additive changes: create missing schemas, workflow APIs, and permissions.
6. Preview risky multi-resource changes before applying them.
7. Test every created route and summarize what changed.

## Guardrails

- Never write raw tokens into source files, docs, screenshots, git commits, or logs.
- Do not ask for permanent owner credentials when a temporary automation token is available.
- Do not use direct database access for project automation.
`;
}

function isAutomationTokenCreateResponse(body: unknown): body is {
  token: string;
  tokenRecord: { expiresAt: string; scopes: string[] };
} {
  return typeof body === "object"
    && body !== null
    && "token" in body
    && typeof body.token === "string"
    && "tokenRecord" in body
    && typeof body.tokenRecord === "object"
    && body.tokenRecord !== null
    && "expiresAt" in body.tokenRecord
    && typeof body.tokenRecord.expiresAt === "string"
    && "scopes" in body.tokenRecord
    && Array.isArray(body.tokenRecord.scopes)
    && body.tokenRecord.scopes.every((scope) => typeof scope === "string");
}

async function openRuntimeDatabase(config: { databasePath: string; databaseProvider: string; databaseUrl?: string }): Promise<ApiagexDatabase> {
  if (config.databaseProvider === "postgres") return openPostgresAdapter(config.databaseUrl, { migrate: true });
  if (config.databaseProvider === "mysql") return openMySqlAdapter(config.databaseUrl, { migrate: true });
  return openMigratedSqliteAdapter(config.databasePath);
}

async function generateTypes(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const parsed = parseTypesArgs(args);
  if (typeof parsed === "string") return fail(parsed);
  const cwd = options.cwd ?? process.cwd();
  const env = { ...await readProjectEnv(cwd), ...process.env, INIT_CWD: cwd, ...options.env };
  const config = resolveLocalServerConfig(env, cwd);
  await ensureLocalServerPaths(config);
  const database = await openRuntimeDatabase(config);
  try {
    const result = await generateApiagexTypes(database, {
      cwd,
      ...(parsed.outFile === undefined ? {} : { outFile: parsed.outFile }),
    });
    return ok(`Generated ${result.schemaCount} schema type${result.schemaCount === 1 ? "" : "s"} at ${result.outFile}\n`);
  } finally {
    await database.close();
  }
}

function parseTypesArgs(args: string[]): { outFile?: string } | string {
  const parsed: { outFile?: string } = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? "";
    if (arg === "--out" || arg === "-o") {
      const outFile = args[index + 1];
      if (!outFile) return "Use apiagex types --out <path>.";
      parsed.outFile = outFile;
      index += 1;
    } else if (arg.startsWith("-")) return `Unknown apiagex types option: ${arg}`;
    else return `Unknown apiagex types argument: ${arg}`;
  }
  return parsed;
}

async function readProjectEnv(cwd: string): Promise<Record<string, string>> {
  try {
    return parseDotEnv(await readFile(join(cwd, ".env"), "utf8"));
  } catch (error) {
    if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return {};
    throw error;
  }
}

function parseDotEnv(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    if (!key) continue;
    env[key] = unquoteEnvValue(line.slice(separator + 1).trim());
  }
  return env;
}

function unquoteEnvValue(value: string): string {
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1);
  }
  return value;
}

function databaseLocationLine(config: { databasePath: string; databaseProvider: string; databaseUrl?: string }): string {
  if (config.databaseProvider === "postgres") return "Apiagex database provider: postgres";
  if (config.databaseProvider === "mysql") return "Apiagex database provider: mysql";
  return `Apiagex database path: ${config.databasePath}`;
}

function startupErrorMessage(host: string, port: number, error: unknown): string {
  const code = typeof error === "object" && error && "code" in error ? String(error.code) : "";
  const detail = error instanceof Error ? error.message : String(error);
  if (code === "EADDRINUSE") {
    return `Apiagex failed to start: http://${host}:${port} is already in use. Stop the other server or set PORT to another value.`;
  }
  return `Apiagex failed to start on http://${host}:${port}: ${detail}`;
}

async function bootstrapInitialOwner(database: ApiagexDatabase, owner: { email: string; password: string }): Promise<void> {
  try {
    await bootstrapOwner(database, owner);
    console.log(`Apiagex owner created: ${owner.email}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : "OWNER_BOOTSTRAP_FAILED";
    if (message !== "OWNER_ALREADY_BOOTSTRAPPED") throw error;
    console.log("Apiagex owner already exists; skipping owner bootstrap.");
  }
}

async function smoke(options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const server = createServer();
  const response = await server.inject({ method: "GET", url: "/api/health" });
  await server.close();
  if (response.statusCode !== 200 || response.json().ok !== true) {
    return fail("Apiagex smoke failed: /api/health did not return ok.\n");
  }
  const cwd = options.cwd ?? process.cwd();
  return ok(`Apiagex smoke passed in ${cwd}.\n`);
}

function ok(stdout: string): RuntimeCliResult {
  return { code: 0, stderr: "", stdout };
}

function fail(stderr: string): RuntimeCliResult {
  return { code: 1, stderr, stdout: "" };
}
