import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { createServer } from "./app.js";
import { ensureLocalServerPaths, resolveLocalServerConfig } from "./server-config.js";
import { bootstrapOwner } from "./owner-bootstrap.js";
import { generateApiagexTypes } from "./typegen.js";
import {
  openMigratedSqliteAdapter,
  openMySqlAdapter,
  openPostgresAdapter,
  type ApiagexDatabase,
} from "@apiagex/database";
import type { RuntimeCliOptions, RuntimeCliResult, StartedApiagexServer, StartServerOptions } from "./runtime.type.js";

const runtimeVersion = "0.8.15";

export async function startApiagex(options: StartServerOptions = {}): Promise<StartedApiagexServer | undefined> {
  return startApiagexServer(options);
}

export async function startApiagexServer(options: StartServerOptions = {}): Promise<StartedApiagexServer | undefined> {
  const env = options.env ?? process.env;
  const host = options.host ?? env.HOST ?? "127.0.0.1";
  const port = options.port ?? Number(env.PORT ?? 4000);
  const config = options.config ?? resolveLocalServerConfig(env, options.cwd ?? process.cwd());
  await ensureLocalServerPaths(config);
  const database = await openRuntimeDatabase(config);
  if (options.initialOwner) await bootstrapInitialOwner(database, options.initialOwner);
  const server = createServer({
    ...config,
    database,
    ...(options.customRoutes ? { customRoutes: options.customRoutes } : {}),
  });
  try {
    await server.listen({ host, port });
    console.log(`Apiagex listening on http://${host}:${port}`);
    console.log(databaseLocationLine(config));
    console.log(`Apiagex uploads path: ${config.uploadsPath}`);
    return server;
  } catch (error) {
    server.log.error(error);
    console.error(startupErrorMessage(host, port, error));
    process.exitCode = 1;
    return undefined;
  }
}

export async function runRuntimeCli(args: string[], options: RuntimeCliOptions = {}): Promise<RuntimeCliResult> {
  const command = args[0] ?? "--help";
  if (command === "--help" || command === "-h") return ok(renderRuntimeHelp());
  if (command === "--version" || command === "-v") return ok(`apiagex ${runtimeVersion}\n`);
  if (command === "smoke") return smoke(options);
  if (command === "types") return generateTypes(args.slice(1), options);
  if (command === "build") return ok("Apiagex runtime does not need a project build. Run apiagex smoke to verify.\n");
  if (command === "dev" || command === "start") {
    const startOptions = {
      ...(options.cwd === undefined ? {} : { cwd: options.cwd }),
      ...(options.env === undefined ? {} : { env: options.env }),
    };
    await startApiagexServer(startOptions);
    return ok("");
  }
  return fail(`Unknown apiagex command: ${command}\n\n${renderRuntimeHelp()}`);
}

export function renderRuntimeHelp(): string {
  return `apiagex ${runtimeVersion}

Usage:
  apiagex dev       Start the Apiagex server for local development.
  apiagex start     Start the Apiagex server.
  apiagex smoke     Verify the runtime health route without a long-running server.
  apiagex types     Generate TypeScript helpers from the current database schemas.
  apiagex build     Print build guidance for generated projects.

Options:
  --out <path>       apiagex types output file. Default: src/apiagex-types.ts.
  -h, --help        Show help.
  -v, --version     Show version.

Environment:
  APIAGEX_DATABASE_PROVIDER sqlite, postgres, or mysql. Default: sqlite.
  PORT                    Server port. Default: 4000.
  HOST                    Server host. Default: 127.0.0.1.
  APIAGEX_DATABASE_PATH   SQLite path. Default: .apiagex/apiagex.sqlite.
  APIAGEX_DATABASE_URL    PostgreSQL/MySQL URL when provider is postgres or mysql.
  APIAGEX_UPLOADS_PATH    Uploads path. Default: .apiagex/uploads.
  APIAGEX_SECRET          App secret generated by create-apiagex.
  APIAGEX_OWNER_EMAIL     Optional first owner bootstrap email.
  APIAGEX_OWNER_PASSWORD  Optional first owner bootstrap password. Remove after first start.
`;
}

async function openRuntimeDatabase(config: { databasePath: string; databaseProvider: string; databaseUrl?: string }): Promise<ApiagexDatabase> {
  if (config.databaseProvider === "postgres") return openPostgresAdapter(config.databaseUrl, { migrate: true });
  if (config.databaseProvider === "mysql") return openMySqlAdapter(config.databaseUrl, { migrate: true });
  return openMigratedSqliteAdapter(config.databasePath);
}

async function generateTypes(args: string[], options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const parsed = parseTypesArgs(args);
  if (typeof parsed === "string") return fail(parsed);
  const cwd = options.cwd ?? process.cwd();
  const env = { ...await readProjectEnv(cwd), ...process.env, INIT_CWD: cwd, ...options.env };
  const config = resolveLocalServerConfig(env, cwd);
  await ensureLocalServerPaths(config);
  const database = await openRuntimeDatabase(config);
  try {
    const result = await generateApiagexTypes(database, {
      cwd,
      ...(parsed.outFile === undefined ? {} : { outFile: parsed.outFile }),
    });
    return ok(`Generated ${result.schemaCount} schema type${result.schemaCount === 1 ? "" : "s"} at ${result.outFile}\n`);
  } finally {
    await database.close();
  }
}

function parseTypesArgs(args: string[]): { outFile?: string } | string {
  const parsed: { outFile?: string } = {};
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index] ?? "";
    if (arg === "--out" || arg === "-o") {
      const outFile = args[index + 1];
      if (!outFile) return "Use apiagex types --out <path>.";
      parsed.outFile = outFile;
      index += 1;
    } else if (arg.startsWith("-")) return `Unknown apiagex types option: ${arg}`;
    else return `Unknown apiagex types argument: ${arg}`;
  }
  return parsed;
}

async function readProjectEnv(cwd: string): Promise<Record<string, string>> {
  try {
    return parseDotEnv(await readFile(join(cwd, ".env"), "utf8"));
  } catch (error) {
    if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return {};
    throw error;
  }
}

function parseDotEnv(content: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    if (!key) continue;
    env[key] = unquoteEnvValue(line.slice(separator + 1).trim());
  }
  return env;
}

function unquoteEnvValue(value: string): string {
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1);
  }
  return value;
}

function databaseLocationLine(config: { databasePath: string; databaseProvider: string; databaseUrl?: string }): string {
  if (config.databaseProvider === "postgres") return "Apiagex database provider: postgres";
  if (config.databaseProvider === "mysql") return "Apiagex database provider: mysql";
  return `Apiagex database path: ${config.databasePath}`;
}

function startupErrorMessage(host: string, port: number, error: unknown): string {
  const code = typeof error === "object" && error && "code" in error ? String(error.code) : "";
  const detail = error instanceof Error ? error.message : String(error);
  if (code === "EADDRINUSE") {
    return `Apiagex failed to start: http://${host}:${port} is already in use. Stop the other server or set PORT to another value.`;
  }
  return `Apiagex failed to start on http://${host}:${port}: ${detail}`;
}

async function bootstrapInitialOwner(database: ApiagexDatabase, owner: { email: string; password: string }): Promise<void> {
  try {
    await bootstrapOwner(database, owner);
    console.log(`Apiagex owner created: ${owner.email}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : "OWNER_BOOTSTRAP_FAILED";
    if (message !== "OWNER_ALREADY_BOOTSTRAPPED") throw error;
    console.log("Apiagex owner already exists; skipping owner bootstrap.");
  }
}

async function smoke(options: RuntimeCliOptions): Promise<RuntimeCliResult> {
  const server = createServer();
  const response = await server.inject({ method: "GET", url: "/api/health" });
  await server.close();
  if (response.statusCode !== 200 || response.json().ok !== true) {
    return fail("Apiagex smoke failed: /api/health did not return ok.\n");
  }
  const cwd = options.cwd ?? process.cwd();
  return ok(`Apiagex smoke passed in ${cwd}.\n`);
}

function ok(stdout: string): RuntimeCliResult {
  return { code: 0, stderr: "", stdout };
}

function fail(stderr: string): RuntimeCliResult {
  return { code: 1, stderr, stdout: "" };
}
