import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { listSchemas, type ApiagexDatabase, type FieldRecord, type SchemaRecord } from "@apiagex/database";

export type GenerateApiagexTypesOptions = {
  cwd?: string;
  outFile?: string;
};

export type GenerateApiagexTypesResult = {
  outFile: string;
  schemaCount: number;
};

export async function generateApiagexTypes(
  database: ApiagexDatabase,
  options: GenerateApiagexTypesOptions = {},
): Promise<GenerateApiagexTypesResult> {
  const cwd = options.cwd ?? process.cwd();
  const outFile = resolve(cwd, options.outFile ?? "src/apiagex-types.ts");
  const schemas = await listSchemas(database);
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, renderApiagexTypes(schemas), "utf8");
  return { outFile, schemaCount: schemas.length };
}

export function renderApiagexTypes(schemas: SchemaRecord[]): string {
  const sortedSchemas = [...schemas].sort((left, right) => left.slug.localeCompare(right.slug));
  const slugValues = sortedSchemas.map((schema) => `  ${JSON.stringify(schema.slug)},`).join("\n");
  const typeBlocks = sortedSchemas.map(renderSchemaType).join("\n\n");
  const mapEntries = sortedSchemas
    .map((schema) => `  ${propertyKey(schema.slug)}: ${schemaTypeName(schema)};`)
    .join("\n");

  return `/* eslint-disable */
// Generated by apiagex types. Do not edit manually.
import type { ApiagexCustomRouteContext } from "@apiagex/server";

export const apiagexSchemaSlugs = [
${slugValues}
] as const;

export type ApiagexSchemaSlug = typeof apiagexSchemaSlugs[number];

${typeBlocks || "export type ApiagexNoSchemasYet = Record<string, never>;"}

export type ApiagexEntryDataBySlug = {
${mapEntries}
};

type ApiagexBaseEntry = NonNullable<Awaited<ReturnType<ApiagexCustomRouteContext["entries"]["getById"]>>>;
type ApiagexEntryQueryOptions = Parameters<ApiagexCustomRouteContext["entries"]["query"]>[1];

export type ApiagexEntryFor<TSlug extends ApiagexSchemaSlug> =
  ApiagexBaseEntry & { data: ApiagexEntryDataBySlug[TSlug] };

export async function getApiagexSchema<TSlug extends ApiagexSchemaSlug>(
  apiagex: ApiagexCustomRouteContext,
  slug: TSlug,
) {
  const schema = await apiagex.schemas.getBySlug(slug);
  if (!schema) throw new Error(\`APIAGEX_SCHEMA_NOT_FOUND: \${slug}\`);
  return schema;
}

export async function queryApiagexEntries<TSlug extends ApiagexSchemaSlug>(
  apiagex: ApiagexCustomRouteContext,
  slug: TSlug,
  options?: ApiagexEntryQueryOptions,
) {
  const schema = await getApiagexSchema(apiagex, slug);
  const result = await apiagex.entries.query(schema.id, options);
  return {
    ...result,
    entries: result.entries as ApiagexEntryFor<TSlug>[],
  };
}

export function typedApiagexEntry<TSlug extends ApiagexSchemaSlug>(
  entry: ApiagexBaseEntry | undefined,
): ApiagexEntryFor<TSlug> | undefined {
  return entry as ApiagexEntryFor<TSlug> | undefined;
}
`;
}

function renderSchemaType(schema: SchemaRecord): string {
  const fields = [...schema.fields].sort((left, right) => left.position - right.position);
  const lines = fields.map(renderField).join("\n");
  return `export type ${schemaTypeName(schema)} = {
${lines || "  [key: string]: never;"}
};`;
}

function renderField(field: FieldRecord): string {
  const optional = field.required ? "" : "?";
  const type = field.required ? fieldType(field) : `${fieldType(field)} | null`;
  return `  ${propertyKey(field.slug)}${optional}: ${type};`;
}

function fieldType(field: FieldRecord): string {
  if (field.type === "number") return "number";
  if (field.type === "boolean") return "boolean";
  if (field.type === "json") return "unknown";
  if (field.type === "relation") return relationFieldType(field);
  return "string";
}

function relationFieldType(field: FieldRecord): string {
  const relationType = field.relationType ?? "manyToOne";
  if (relationType === "oneToMany" || relationType === "manyToMany") return "string[]";
  return "string";
}

function schemaTypeName(schema: SchemaRecord): string {
  return `${pascalCase(schema.slug)}Data`;
}

function pascalCase(value: string): string {
  const name = value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return name || "Schema";
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}
